// <auto-generated />
using aplicacionEjemplo1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace aplicacionEjemplo1.Migrations.DALMySQL
{
    [DbContext(typeof(DALMySQLContext))]
    partial class DALMySQLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("aplicacionEjemplo1.Pelicula", b =>
                {
                    b.Property<string>("NombrePelicula")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255);

                    b.Property<string>("ApellidoDirector")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("NombreDirector")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("NombrePelicula");

                    b.ToTable("pelicula");
                });
#pragma warning restore 612, 618
        }
    }
}
